FROM mcr.microsoft.com/devcontainers/dotnet:7.0

# Install additional tools if needed
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends curl